package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	sdk "github.com/your-org/deployserver/sdk"
)

var (
	_ resource.Resource              = (*apiTokenResource)(nil)
	_ resource.ResourceWithConfigure = (*apiTokenResource)(nil)
)

func NewAPITokenResource() resource.Resource { return &apiTokenResource{} }

type apiTokenResource struct {
	client *sdk.Client
}

type apiTokenModel struct {
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	ExpiresInDays types.Int64  `tfsdk:"expires_in_days"`
	Roles         types.List   `tfsdk:"roles"`
	Token         types.String `tfsdk:"token"`
	Prefix        types.String `tfsdk:"prefix"`
	ScopeRoles    types.List   `tfsdk:"scope_roles"`
	CreatedAt     types.String `tfsdk:"created_at"`
}

func (r *apiTokenResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_api_token"
}

func (r *apiTokenResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	// Every input is immutable: the secret only exists at creation, so any
	// change recreates the token (and revokes the old one on destroy).
	replaceStr := []planmodifier.String{stringplanmodifier.RequiresReplace()}
	resp.Schema = schema.Schema{
		MarkdownDescription: "A long-lived API token. The secret is generated by the server and is only " +
			"available at creation — Terraform stores it (sensitively) in state. Optionally scope it to a " +
			"subset of your roles for least privilege.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Token UUID.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Human label.",
				Required:            true,
				PlanModifiers:       replaceStr,
			},
			"expires_in_days": schema.Int64Attribute{
				MarkdownDescription: "Days until expiry. Omit for a non-expiring token.",
				Optional:            true,
				PlanModifiers:       []planmodifier.Int64{int64planmodifier.RequiresReplace()},
			},
			"roles": schema.ListAttribute{
				MarkdownDescription: "Restrict the token to a subset of your roles (least privilege). " +
					"Omit for your full permissions.",
				Optional:      true,
				ElementType:   types.StringType,
				PlanModifiers: []planmodifier.List{listplanmodifier.RequiresReplace()},
			},
			"token": schema.StringAttribute{
				MarkdownDescription: "The plaintext secret. Available only at creation; use it for " +
					"`DEPLOY_API_TOKEN`.",
				Computed:      true,
				Sensitive:     true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"prefix": schema.StringAttribute{
				MarkdownDescription: "Short display prefix, e.g. `dpsk_ab12cd`.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"scope_roles": schema.ListAttribute{
				MarkdownDescription: "Effective role scope (empty = full owner permissions).",
				Computed:            true,
				ElementType:         types.StringType,
				PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
			"created_at": schema.StringAttribute{
				MarkdownDescription: "Creation timestamp (RFC 3339).",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *apiTokenResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromProvider(req.ProviderData, &resp.Diagnostics)
}

func (r *apiTokenResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan apiTokenModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	in := sdk.CreateAPITokenInput{
		Name:          plan.Name.ValueString(),
		ExpiresInDays: optInt(plan.ExpiresInDays),
	}
	if !plan.Roles.IsNull() && !plan.Roles.IsUnknown() {
		resp.Diagnostics.Append(plan.Roles.ElementsAs(ctx, &in.Roles, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
	}
	created, err := r.client.CreateAPIToken(ctx, in)
	if err != nil {
		resp.Diagnostics.AddError("Create API token failed", err.Error())
		return
	}
	// Preserve the plan's roles input; everything else comes from the server.
	state := apiTokenFromAPI(&created.APIToken, plan.Roles)
	state.Token = types.StringValue(created.Token)
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *apiTokenResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state apiTokenModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	toks, err := r.client.ListAPITokens(ctx)
	if err != nil {
		resp.Diagnostics.AddError("Read API token failed", err.Error())
		return
	}
	id := state.ID.ValueString()
	for i := range toks {
		if toks[i].ID != id {
			continue
		}
		if toks[i].RevokedAt != nil {
			resp.State.RemoveResource(ctx) // revoked out-of-band -> recreate
			return
		}
		refreshed := apiTokenFromAPI(&toks[i], state.Roles)
		refreshed.Token = state.Token                 // secret is not refetchable
		refreshed.ExpiresInDays = state.ExpiresInDays // input, not returned by the API
		resp.Diagnostics.Append(resp.State.Set(ctx, refreshed)...)
		return
	}
	resp.State.RemoveResource(ctx) // gone
}

// Update never runs: every configurable attribute forces replacement. It
// is required to satisfy the resource.Resource interface.
func (r *apiTokenResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update not supported", "API tokens are immutable; changes recreate the token.")
}

func (r *apiTokenResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state apiTokenModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.RevokeAPIToken(ctx, state.ID.ValueString()); err != nil && !sdk.IsNotFound(err) {
		resp.Diagnostics.AddError("Revoke API token failed", err.Error())
	}
}

// apiTokenFromAPI maps the server record onto the model, carrying the
// caller's `roles` input through unchanged (the API echoes back the
// effective `scope_roles`, not the requested `roles`).
func apiTokenFromAPI(t *sdk.APIToken, roles types.List) apiTokenModel {
	if roles.IsUnknown() {
		roles = types.ListNull(types.StringType)
	}
	m := apiTokenModel{
		ID:         types.StringValue(t.ID),
		Name:       types.StringValue(t.Name),
		Roles:      roles,
		Prefix:     types.StringValue(t.Prefix),
		ScopeRoles: stringListValue(t.ScopeRoles),
		CreatedAt:  types.StringValue(t.CreatedAt.Format(rfc3339)),
	}
	return m
}
